version: '3.8'

services:
  gemini-gen-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gemini-gen-app
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - gemini-net

  nginx:
    image: nginx:alpine
    container_name: gemini-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gemini-gen-app
    restart: unless-stopped
    networks:
      - gemini-net

networks:
  gemini-net:
    driver: bridge